# Generated by Django 5.0.7 on 2024-07-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
